[config]
type = "pipeline"
chartbook_format_version = "0.0.2"

[site]
title = "p12_michelacci_ferreira_2026"
author = "Michelacci and Ferreira"
copyright = "2025"
logo_path = ""
favicon_path = ""

[pipeline]
id = "SE"
pipeline_name = "p12_michelacci_ferreira_2026"
pipeline_description = "replication of paper "Segmented Arbitrage" by Emil Siriwardane, Adi Sunderam, and Jonathan Wallen."
lead_pipeline_developer = "Michelacci and Ferreira"
contributors = ["Michelacci and Ferreira"]
software_modules_command = "module load anaconda3/3.11.4 TeXLive/2023"
runs_on_grid_or_windows_or_other = "Windows/Linux/MacOS"
git_repo_URL = ""
README_file_path = "./README.md"

[notebooks]


[notebooks.01_example_notebook_interactive]
notebook_name = "Example Notebook Interactive"
notebook_description = "Example notebook for demonstrating how to construct a Chartbook notebook."
notebook_path = "_output/01_example_notebook_interactive.ipynb"


[notebooks.02_example_with_dependencies]
notebook_name = "Example Notebook with Dependencies"
notebook_description = "Example notebook demonstrating dependencies on data pulls."
notebook_path = "_output/02_example_with_dependencies.ipynb"




[dataframes]


[charts]

